name:                L4
version:             0.1.0.0
github:              "githubuser/L4"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/L4#readme>

dependencies:
- base >= 4.7 && < 5
#- protolude
#- classy-prelude
- deepseq
- directory
- filepath
- text
- containers
- unordered-containers
- aeson
- pretty-simple
#- game-probability
- mtl
- time-lens
- time
- lens
- lens-aeson
#- data-easy
- random >= 1.1
- bytestring >= 0.10.10.0
- extensible-exceptions >= 0.1.1.0
- safe-exceptions
- OpenGL
- GLUT
- array 
#- 3d-graphics-examples
- code-page
- happstack-server
- process
- yesod
- hjsmin
- http-conduit
- conduit
- conduit-extra
- snap-server
- snap-core
- base16-bytestring
- base64-bytestring
- email-validate
- QuickCheck
- utf8-string
- serialise
- cereal
- stm
#- byte-order
- byteorder
- bytedump


default-extensions:
#- NoImplicitPrelude
- OverloadedStrings
#- XScopedTypeVariables
#- QuasiQuotes
#- TemplateHaskell
- FlexibleContexts
- DeriveGeneric

library:
  source-dirs: src

executables:
  L4-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - L4

tests:
  L4-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - L4
